/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form_view;

import DAO.BanHangDAO;
import DAO.NhanVienDAO;
import DAO.SanPhamDAO;
import POJO.HoaDonXuat;
import POJO.NhanVien;
import POJO.ChiTietHoaDonXuat;
import POJO.SanPham;

import java.sql.*;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class BanHang_form extends javax.swing.JFrame {

    Vector tblData = new Vector();
    Vector tblTitle = new Vector();
    Vector tblData1 = new Vector();
    Vector tblTitle1 = new Vector();
    Vector tblData2 = new Vector();
    Vector tblTitle2 = new Vector();
    Vector tblData3 = new Vector();
    Vector tblTitle3 = new Vector();
    DefaultTableModel tblModel;
    
    static ArrayList<NhanVien> dsnv = NhanVienDAO.getDSNV();
    static ArrayList<HoaDonXuat> dshdx = BanHangDAO.getDSHDX();
    static ArrayList<SanPham> dssp = SanPhamDAO.getDSSP();
    static ArrayList<ChiTietHoaDonXuat> dscthdx = BanHangDAO.getDSCTHDX();
    
    public BanHang_form() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        bangnhanvien();
        laydulieunhanvien(dsnv);
        banghoadonxuat();
        laydulieuhoadonxuat(dshdx);
        txt_mahdx.setEnabled(false);
        
        bangsanpham();
        laydulieusanpham(dssp);
        bangchitiethoadonxuat();
        laydulieuchitiethoadonxuat(dscthdx);
        txt_Macthdx.setEnabled(false);
    }
    
    public void bangnhanvien(){
        tblTitle.add("Mã nhân viên"); tblTitle.add("Tên nhân viên"); tblTitle.add("Tài khoản"); tblTitle.add("Mật khẩu"); tblTitle.add("Số điện thoại"); tblTitle.add("Chức vụ");
    }
    
    public void laydulieunhanvien(ArrayList<NhanVien> dsnv){
        tblData.removeAllElements();
        for(NhanVien b : dsnv){
            Vector v = new Vector();
            v.add(b.getManv()); v.add(b.getHoten()); v.add(b.getTaikhoan());v.add(b.getMatkhau()); v.add(b.getSdt()); v.add(b.getChucvu());
            tblData.add(v);
        }
        table_nhanvien.setModel(new DefaultTableModel(tblData, tblTitle));
    }
    public void banghoadonxuat(){
        tblTitle1.add("Mã hóa đơn"); tblTitle1.add("Mã nhân viên"); tblTitle1.add("Ngày xuất"); tblTitle1.add("Tên khách hàng"); tblTitle1.add("Số điện thoại"); tblTitle1.add("Tổng tiền");
    }
    
    public void laydulieuhoadonxuat(ArrayList<HoaDonXuat> dshdx){
        tblData1.removeAllElements();
        for(HoaDonXuat b : dshdx){
            Vector v = new Vector();
            v.add(b.getMahdx()); v.add(b.getManv()); v.add(b.getNgayxuat());v.add(b.getHotenkh()); v.add(b.getSdt()); v.add(b.getTongtien());
            tblData1.add(v);
        }
        table_hoadonxuat.setModel(new DefaultTableModel(tblData1, tblTitle1));
    }
    
    public void bangsanpham(){
        tblTitle2.add("Mã sản phẩm"); tblTitle2.add("Tên sản phẩm"); tblTitle2.add("Giá tiền"); tblTitle2.add("Số lượng"); tblTitle2.add("Mã nhà cung cấp"); tblTitle2.add("Loại sản phẩm");
    }
    
    public void laydulieusanpham(ArrayList<SanPham> dssp){
        tblData2.removeAllElements();
        for(SanPham b : dssp){
            Vector v = new Vector();
            v.add(b.getMasp()); v.add(b.getTensp()); v.add(b.getGiatien());v.add(b.getSoluong()); v.add(b.getMancc()); v.add(b.getLoaisp());
            tblData2.add(v);
        }
        table_sanpham.setModel(new DefaultTableModel(tblData2, tblTitle2));
    }
    public void bangchitiethoadonxuat(){
        tblTitle3.add("Mã chi tiết hdx"); tblTitle3.add("Mã hóa đơn xuất"); tblTitle3.add("Mã sản phẩm"); tblTitle3.add("Số lượng"); tblTitle3.add("Đơn giá xuất"); tblTitle3.add("Thành tiền");
    }
    
    public void laydulieuchitiethoadonxuat(ArrayList<ChiTietHoaDonXuat> dscthdx){
        tblData3.removeAllElements();
        for(ChiTietHoaDonXuat b : dscthdx){
            Vector v = new Vector();
            v.add(b.getMacthdx()); v.add(b.getMahdx()); v.add(b.getMasp());v.add(b.getSoluong()); v.add(b.getDongiaxuat()); v.add(b.getThanhtien());
            tblData3.add(v);
        }
        table_chitiethoadonxuat.setModel(new DefaultTableModel(tblData3, tblTitle3));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_nhanvien = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_hoadonxuat = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_ngayxuat = new javax.swing.JTextField();
        txt_hotenkh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_tongtien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_mahdx = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_manv = new javax.swing.JTextField();
        bt_them = new javax.swing.JButton();
        bt_xoa = new javax.swing.JButton();
        bt_sua = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txt_tennv = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_sanpham = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_chitiethoadonxuat = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_Macthdx = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_Mahdx = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_Masp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_Soluong = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_Dongiaxuat = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_Thanhtien = new javax.swing.JTextField();
        bt_Them = new javax.swing.JButton();
        bt_Xoa = new javax.swing.JButton();
        bt_Sua = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txt_tensp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Hóa Đơn Xuất");

        table_nhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_nhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_nhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_nhanvien);

        table_hoadonxuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_hoadonxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_hoadonxuatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_hoadonxuat);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel4.setText("Ngày xuất:");

        jLabel5.setText("Họ tên khách hàng:");

        jLabel6.setText("Số điện thoại:");

        jLabel7.setText("Tổng tiền:");

        jLabel2.setText("Mã hóa đơn xuất:");

        jLabel3.setText("Mã nhân viên:");

        bt_them.setText("Thêm");
        bt_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_themActionPerformed(evt);
            }
        });

        bt_xoa.setText("Xóa");
        bt_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xoaActionPerformed(evt);
            }
        });

        bt_sua.setText("Sửa");
        bt_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_suaActionPerformed(evt);
            }
        });

        jLabel16.setText("Tên nhân viên:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(bt_them))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_mahdx, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(bt_xoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_sua))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_ngayxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(txt_hotenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_manv, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_tennv, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_mahdx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_manv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_tennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_ngayxuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_hotenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_xoa)
                    .addComponent(bt_sua)
                    .addComponent(bt_them))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(506, 506, 506)
                        .addComponent(jLabel1)))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(467, 467, 467))
        );

        jTabbedPane1.addTab("HoaDonXuat", jPanel1);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Chi Tiết Hóa Đơn Xuất");

        table_sanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_sanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_sanphamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_sanpham);

        table_chitiethoadonxuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_chitiethoadonxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_chitiethoadonxuatMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table_chitiethoadonxuat);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setText("Mã chi tiết hdx:");

        jLabel10.setText("Mã hóa đơn xuất:");

        jLabel11.setText("Mã sản phẩm:");

        jLabel12.setText("Số lượng:");

        jLabel13.setText("Đơn giá xuất:");

        jLabel14.setText("Thành tiền:");

        bt_Them.setText("Thêm");
        bt_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ThemActionPerformed(evt);
            }
        });

        bt_Xoa.setText("Xóa");
        bt_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_XoaActionPerformed(evt);
            }
        });

        bt_Sua.setText("Sửa");
        bt_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SuaActionPerformed(evt);
            }
        });

        jLabel15.setText("Tên sản phẩm:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_Dongiaxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_Soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_Macthdx, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Mahdx, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_Thanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Masp, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txt_tensp))))
                        .addGap(0, 59, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(bt_Them)
                        .addGap(45, 45, 45)
                        .addComponent(bt_Xoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_Sua)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_Macthdx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_Mahdx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_Masp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_tensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_Soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_Dongiaxuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_Thanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Them)
                    .addComponent(bt_Xoa)
                    .addComponent(bt_Sua))
                .addGap(96, 96, 96))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(jLabel8)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(164, 164, 164))
        );

        jTabbedPane1.addTab("ChiTietHoaDonXuat", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_suaActionPerformed
        if(KiemTraTXT()){
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn sửa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String sql = "update HOADONXUAT set  manv= N'"+txt_manv.getText().trim()+"', ngayxuat=N'"+txt_ngayxuat.getText().trim()+"', hotenkh='"
                +txt_hotenkh.getText().trim()+"', sdt='"+txt_sdt.getText().trim()+"', tongtien=N'"+txt_tongtien.getText().trim()+"' where mahdx='"+txt_mahdx.getText().trim()+"'";
                BanHangDAO.ThemXoaSuaHoaDonXuat(sql);
                dshdx = BanHangDAO.getDSHDX();
                laydulieuhoadonxuat(dshdx);
            }
        }
    }//GEN-LAST:event_bt_suaActionPerformed

    private void bt_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xoaActionPerformed
        int i = table_hoadonxuat.getSelectedRow();
        if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            String sql = "delete from HOADONXUAT where mahdx= '"+txt_mahdx.getText().trim()+"'";
            if(BanHangDAO.ThemXoaSuaHoaDonXuat(sql)!=-1)
            {
                dshdx = BanHangDAO.getDSHDX();
                laydulieuhoadonxuat(dshdx);
            }
            else
            JOptionPane.showMessageDialog(this, "Hóa đơn này không thể xóa", "Thông báo", 2);

        }
    }//GEN-LAST:event_bt_xoaActionPerformed

    private void bt_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_themActionPerformed
        String ma = txt_manv.getText().trim();
        String ngay = txt_ngayxuat.getText().trim();
        String ten = txt_hotenkh.getText().trim();
        String sdt= txt_sdt.getText().trim();
        String tongtien= txt_tongtien.getText().trim();
        if(KiemTraTXT()){
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String sql = "INSERT INTO HOADONXUAT VALUES('"+ma+"', N'"+ngay+"', N'"+ten+ "', '"+sdt+"', '"+tongtien+"')";
                int kq = BanHangDAO.ThemXoaSuaHoaDonXuat(sql);
                if(kq!=-1)
                {
                    dshdx = BanHangDAO.getDSHDX();
                    new BanHang_form().setVisible(true);
                }
                else
                JOptionPane.showMessageDialog(this, "Mã hóa đơn này đã tồn tại, không thể thêm", "Thông báo", 2);

            }
        }
    }//GEN-LAST:event_bt_themActionPerformed

    private void table_hoadonxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_hoadonxuatMouseClicked
        int i = table_hoadonxuat.getSelectedRow();
        String mahdx = table_hoadonxuat.getValueAt(i, 0).toString().trim();
        String manv = table_hoadonxuat.getValueAt(i, 1).toString().trim();
        String ngayxuat = table_hoadonxuat.getValueAt(i, 2).toString().trim();
        String hotenkh = table_hoadonxuat.getValueAt(i, 3).toString().trim();
        String sdt = table_hoadonxuat.getValueAt(i, 4).toString().trim();
        String tongtien = table_hoadonxuat.getValueAt(i, 5).toString().trim();

        txt_Mahdx.setText(mahdx);
        txt_mahdx.setText(mahdx);
        txt_manv.setText(manv);
        txt_ngayxuat.setText(ngayxuat);
        txt_hotenkh.setText(hotenkh);
        txt_sdt.setText(sdt);
        txt_tongtien.setText(tongtien);
        
        ArrayList<NhanVien> dsnv = NhanVienDAO.TimChiTietNhanVien(manv+"");
        for(NhanVien b : dsnv){
           
            txt_tennv.setText( b.getHoten());
        }
    }//GEN-LAST:event_table_hoadonxuatMouseClicked

    private void table_nhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_nhanvienMouseClicked
        int i = table_nhanvien.getSelectedRow();
        String manv = table_nhanvien.getValueAt(i, 0).toString().trim();

        txt_manv.setText(manv);
        
        ArrayList<NhanVien> dsnv = NhanVienDAO.TimChiTietNhanVien(manv+"");
        for(NhanVien b : dsnv){
           
            txt_tennv.setText( b.getHoten());
        }
    }//GEN-LAST:event_table_nhanvienMouseClicked

    private void bt_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SuaActionPerformed
        if(KiemTraTXT2()){
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn sửa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String sql = "update CHITIETHOADONXUAT set  mahdx= N'"+txt_Mahdx.getText().trim()+"', masp=N'"+txt_Masp.getText().trim()+"', soluongxuat='"
                +txt_Soluong.getText().trim()+"', dongiaxuat='"+txt_Dongiaxuat.getText().trim()+"', thanhtien=N'"+txt_Thanhtien.getText().trim()+"' where macthdx='"+txt_Macthdx.getText().trim()+"'";
                BanHangDAO.ThemXoaSuaHoaDonXuat(sql);
                dscthdx = BanHangDAO.getDSCTHDX();
                laydulieuchitiethoadonxuat(dscthdx);
            }
        }
    }//GEN-LAST:event_bt_SuaActionPerformed

    private void bt_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_XoaActionPerformed
        int i = table_chitiethoadonxuat.getSelectedRow();
        if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            String sql = "delete from CHITIETHOADONXUAT where macthdx= '"+txt_Macthdx.getText().trim()+"'";
            if(BanHangDAO.ThemXoaSuaHoaDonXuat(sql)!=-1)
            {
                dscthdx = BanHangDAO.getDSCTHDX();
                laydulieuchitiethoadonxuat(dscthdx);
            }
            else
            JOptionPane.showMessageDialog(this, "Hóa đơn này không thể xóa", "Thông báo", 2);

        }
    }//GEN-LAST:event_bt_XoaActionPerformed

    private void bt_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ThemActionPerformed
        String mahdx = txt_Mahdx.getText().trim();
        String masp = txt_Masp.getText().trim();
        String soluong = txt_Soluong.getText().trim();
        String dongia = txt_Dongiaxuat.getText().trim();
        String thanhtien= txt_Thanhtien.getText().trim();
        if(KiemTraTXT2()){
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String sql = "INSERT INTO CHITIETHOADONXUAT VALUES('"+mahdx+"', N'"+masp+"', N'"+soluong+ "', '"+dongia+"', '"+thanhtien+"')";
                int kq = BanHangDAO.ThemXoaSuaHoaDonXuat(sql);
                if(kq!=-1)
                {
                    dscthdx = BanHangDAO.getDSCTHDX();
                    new BanHang_form().setVisible(true);
                }
                else
                JOptionPane.showMessageDialog(this, "Mã chi tiết hóa đơn này đã tồn tại, không thể thêm", "Thông báo", 2);

            }
        }
    }//GEN-LAST:event_bt_ThemActionPerformed

    private void table_chitiethoadonxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_chitiethoadonxuatMouseClicked
        int i = table_chitiethoadonxuat.getSelectedRow();
        String macthdx = table_chitiethoadonxuat.getValueAt(i, 0).toString().trim();
        String mahdx = table_chitiethoadonxuat.getValueAt(i, 1).toString().trim();
        String masp = table_chitiethoadonxuat.getValueAt(i, 2).toString().trim();
        String soluong = table_chitiethoadonxuat.getValueAt(i, 3).toString().trim();
        String dongia = table_chitiethoadonxuat.getValueAt(i, 4).toString().trim();
        String thanhtien = table_chitiethoadonxuat.getValueAt(i, 5).toString().trim();

        txt_Macthdx.setText(macthdx);
        txt_Mahdx.setText(mahdx);
        txt_Masp.setText(masp);
        txt_Soluong.setText(soluong);
        txt_Dongiaxuat.setText(dongia);
        txt_Thanhtien.setText(thanhtien);
        
        ArrayList<SanPham> dssp = SanPhamDAO.TimChiTietSanPham(masp+"");
        for(SanPham b : dssp){
           
            txt_tensp.setText( b.getTensp());
        }
    }//GEN-LAST:event_table_chitiethoadonxuatMouseClicked

    private void table_sanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_sanphamMouseClicked
        int i = table_sanpham.getSelectedRow();
        String masp = table_sanpham.getValueAt(i, 0).toString().trim();

        txt_Masp.setText(masp);
        
        ArrayList<SanPham> dssp = SanPhamDAO.TimChiTietSanPham(masp+"");
        for(SanPham b : dssp){
           
            txt_tensp.setText( b.getTensp());
        }
    }//GEN-LAST:event_table_sanphamMouseClicked

    public void taoNgayTuDong()
    {
        txt_ngayxuat.setText(""+java.time.LocalDate.now()); 
        
    }
    
    public Boolean KiemTraTXT(){
        if(txt_manv.getText().equals("") || txt_ngayxuat.getText().equals("")|| txt_hotenkh.getText().equals("") || txt_sdt.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Vui lòng nhập đầy đủ thông tin", "Thông báo",2);
            return false;
        }
        return true;
    }
    public Boolean KiemTraTXT2(){
        if(txt_Mahdx.getText().equals("") || txt_Masp.getText().equals("")|| txt_Soluong.getText().equals("") || txt_Dongiaxuat.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Vui lòng nhập đầy đủ thông tin", "Thông báo",2);
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanHang_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanHang_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanHang_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanHang_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BanHang_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Sua;
    private javax.swing.JButton bt_Them;
    private javax.swing.JButton bt_Xoa;
    private javax.swing.JButton bt_sua;
    private javax.swing.JButton bt_them;
    private javax.swing.JButton bt_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable table_chitiethoadonxuat;
    private javax.swing.JTable table_hoadonxuat;
    private javax.swing.JTable table_nhanvien;
    private javax.swing.JTable table_sanpham;
    private javax.swing.JTextField txt_Dongiaxuat;
    private javax.swing.JTextField txt_Macthdx;
    private javax.swing.JTextField txt_Mahdx;
    private javax.swing.JTextField txt_Masp;
    private javax.swing.JTextField txt_Soluong;
    private javax.swing.JTextField txt_Thanhtien;
    private javax.swing.JTextField txt_hotenkh;
    private javax.swing.JTextField txt_mahdx;
    private javax.swing.JTextField txt_manv;
    private javax.swing.JTextField txt_ngayxuat;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_tennv;
    private javax.swing.JTextField txt_tensp;
    private javax.swing.JTextField txt_tongtien;
    // End of variables declaration//GEN-END:variables
}
